branches:
  only:
    - master
    - develop
    - /release/.*/
    - /hotfix/.*/
    - /feature/.*/

install:
  - git submodule update --init --recursive
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

before_build:
  - nuget restore source/Jobbr.Storage.RavenDB.sln
  - ps: C:\ProgramData\chocolatey\lib\GitVersion.Portable\tools\GitVersion.exe /l console /output buildserver /updateAssemblyInfo

platform: Any CPU
configuration: Release

build:
  parallel: true 
  project: source/Jobbr.Storage.RavenDB.sln

after_build:
  - cmd: nuget pack source\Jobbr.Storage.RavenDB.nuspec -version "%GitVersion_SemVer%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Jobbr.Storage.RavenDB.%GitVersion_SemVer%.nupkg"

test:
  assemblies:
    - '**\bin\Release\Jobbr.Storage.RavenDB.Tests.dll'

deploy:
- provider: NuGet
  server: https://nuget.org
  api_key:
    secure: j72cUd21tWzX9uqbVmqha+x5i83cBkg20Q10MXgT25T7vtrCEdygmdePZbXG25C2
  on:
    appveyor_repo_tag: true